name: build

on:
  push:
    branches:
      - main  # forall push/merge in live
  pull_request:
    branches:
      - "**"  # forall submitted Pull Requests
  workflow_dispatch:
    inputs:

jobs:
  build-matrix:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        opam_file:
          - 'coq-vsu-int63-src.opam'
          - 'coq-vsu-int63-vst-32.opam'
          - 'coq-vsu-int63-vst.opam'
          - 'coq-vsu-int63.opam'
        vst:
          - 'vst-2.8'
        compcert:
          - 'compcert-3.9'
        base:
          - '8.14.1-ocaml-4.12.0-flambda'
          - '8.13.2-ocaml-4.11.2-flambda'
      fail-fast: false  # don't stop jobs if one fails
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          custom_image: tcarstens/coq-vst:${{ matrix.base }}--${{ matrix.compcert }}--${{ matrix.vst }}
          opam_file: ${{ matrix.opam_file }}
          before_install: |
            startGroup "opam pin"
              git clone https://github.com/appliedfm/coq-vsu.git ~/coq-vsu
              opam pin -n -y ~/coq-vsu
              opam pin -n -y .
            endGroup